comment: false
github_checks:
  annotations: false
coverage:
  status:
    patch:
      default:
        target: 60%
    project:
      default:
        threshold: 1%
ignore:
  - "contracts/tools"
  - "contracts/test"
  - "contracts/third_party"
  - "contracts/strategies"
  - "contracts/infrastructure"
  - "contracts/base/strategies"
